### ISSUE TITLE
Exercise 3, npm run e2e fails

### ISSUE THREAD

**Issue by tylerauerbeck** [rht-labs/enablement-docs#486]
If not inside of your `workspace*` project when running `npm run e2e`, the command will fail because it is unable to find a route on port 8084

**Comment by tylerauerbeck** [comment]
We also need to verify that the local apps are still running. Right now I believe that's an assumption that we don't make clear in the instructions.

**Comment by shaheinm** [comment]
Also seeing a race condition occurring when `npm run e2e:jenkins` is run on Jenkins.  The command is an `npm-run-all --parallel` command that starts the selenium server and runs the e2e tests in parallel, but several times I've seen the Selenium server start after an e2e test was attempted.  Here's an example from the logs:

```
> java -Dwebdriver.chrome.driver="$(pwd)/node_modules/chromedriver/lib/chromedriver/chromedriver" -jar $(pwd)/node_modules/selenium-server/lib/runner/selenium-server-standalone-3.11.0.jar -port 8084





> todolist@1.0.0 e2e:ci /tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA

> vue-cli-service e2e --env jenkins --url http://${E2E_TEST_ROUTE}



Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true

17:49:01.138 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'

17:49:01.140 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 8084

2019-08-08 17:49:01.237:INFO::main: Logging initialized @375ms to org.seleniumhq.jetty9.util.log.StdErrLog



[Specs / Important Flag] Test Suite

=======================================



Running:  Testing important flag setting



Error retrieving a new session from the selenium server



Connection refused! Is selenium server started?

{ Error: connect ECONNREFUSED 127.0.0.1:8084

    at Object._errnoException (util.js:992:11)

    at _exceptionWithHostPort (util.js:1014:20)

    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

  code: 'ECONNREFUSED',

  errno: 'ECONNREFUSED',

  syscall: 'connect',

  address: '127.0.0.1',

  port: 8084 }



 ERROR  Error: Command failed: /tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA/node_modules/nightwatch/bin/nightwatch --env jenkins --config /tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js

Error: Command failed: /tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA/node_modules/nightwatch/bin/nightwatch --env jenkins --config /tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js

    at makeError (/tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA/node_modules/execa/index.js:169:9)

    at Promise.all.then.arr (/tmp/workspace/todolist_develop-SGE565TOM5TENGMYXP2HUOWOW7G7J4LXVNE3U3GLVI2J5ZJCAKPA/node_modules/execa/index.js:274:16)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:188:7)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! todolist@1.0.0 e2e:ci: `vue-cli-service e2e --env jenkins --url http://${E2E_TEST_ROUTE}`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the todolist@1.0.0 e2e:ci script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

17:49:01.408 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....

17:49:01.408 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 8084



npm ERR! A complete log of this run can be found in:

npm ERR!     /home/jenkins/.npm/_logs/2019-08-08T17_49_01_407Z-debug.log

npm ERR! code ELIFECYCLE

npm ERR! errno 143

npm ERR! todolist@1.0.0 selenium: `java -Dwebdriver.chrome.driver="$(pwd)/node_modules/chromedriver/lib/chromedriver/chromedriver" -jar $(pwd)/node_modules/selenium-server/lib/runner/selenium-server-standalone-3.11.0.jar -port 8084`

npm ERR! Exit status 143
```

Notice the "Welcome to Selenium for Workgroups" message in the middle of NPM ERR output.

**Comment by tylerauerbeck** [comment]
@springdo @eformat Would either of you have some time to take a look at this race condition issue?

**Comment by shaheinm** [comment]
@tylerauerbeck @springdo @eformat Potential fix for race condition - https://github.com/rht-labs/todolist/pull/4

**Comment by eformat** [comment]
thanks @shaheinm, i will tidy this up for local running of e2e, looks like rht-labs/todolist#4 fixes race condition
